services:
  app:
    build: .
    container_name: php-post-feed-api
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php-post-feed-db
    environment:
      MYSQL_DATABASE: posts_feed
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  wrk:
    build:
      context: ./wrk
    container_name: posts_wrk
    depends_on:
      - app
    entrypoint: ["wrk"]
    profiles: ["test"]

volumes:
  dbdata:
