services:
  nginx:
    image: nginx:alpine
    container_name: php-post-feed-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php
      - db

  php:
    build: .
    container_name: php-post-feed-api
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    command: php-fpm
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php-post-feed-db
    environment:
      MYSQL_DATABASE: posts_feed
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql

  wrk:
    build:
      context: ./wrk
    container_name: posts_wrk
    depends_on:
      - nginx
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  dbdata:
