name: Simple Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and start containers, seed database
      run: |
        make up
        make build-wrk
        sleep 10
        make seed

    - name: Run performance tests
      run: |
        make perf-all || true  # prevent perf test fail from breaking CI if desired

    - name: Show logs
      if: always()
      run: |
        make logs

    - name: Stop containers
      if: always()
      run: |
        make down

