name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
    - name: Start services
      run: |
        make up
        echo "Waiting for services to be ready..."
        sleep 15
        
    - name: Seed database
      run: make seed
      
    - name: Wait for API to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:8000/api/feed.php?user_id=1; do sleep 2; done'
        
    - name: Basic API Health Check
      run: |
        echo "Testing API endpoints..."
        
        # Test feed endpoint
        curl -f "http://localhost:8000/api/feed.php?user_id=1" || exit 1
        echo "✅ Feed endpoint working"
        
        # Test view endpoint
        curl -f -X POST "http://localhost:8000/api/view.php" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "user_id=1&post_id=1" || exit 1
        echo "✅ View endpoint working"
        
    - name: Run Performance Tests
      run: |
        echo "Running performance tests..."
        make perf-view
        make perf-feed
        
    - name: Cleanup
      if: always()
      run: make down